# Generated by Django 5.1.7 on 2025-03-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_country_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
